-- 简化版海牙平台数据库初始化脚本
-- 用于创建所有服务的数据库和基本表结构

-- 创建所有服务数据库
CREATE DATABASE IF NOT EXISTS haiya_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_video CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_comment CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_like CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_follow CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_gateway CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_registry CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_message CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_live CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_recommend CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_search CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_payment CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_ecommerce CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_ad CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_ad_analytics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_analytics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_ar_vr CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_article CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_audio CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_bi CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_camera CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_campaign CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_cart CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_content_security CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_copyright CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_creator_tools CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_dashboard CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_data_collector CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_data_warehouse CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_database_sharding CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_distributed_transaction CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_editor CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_effect CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_feature_engineering CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_gift CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_group CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_im CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_live_interaction CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_localization CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_logistics CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_media_processing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_mesh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_minor_protection CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_ml_platform CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_moderation CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_notification CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_order CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_product CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_qanda CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_real_time_processing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_storage CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_story CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_supply_chain CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_topic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_transcoder CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_translation CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS haiya_virtual_tryon CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 创建用户并授权
CREATE USER IF NOT EXISTS 'haiya'@'%' IDENTIFIED BY 'haiya123';
CREATE USER IF NOT EXISTS 'haiya'@'localhost' IDENTIFIED BY 'haiya123';

-- 授权用户访问所有相关数据库
GRANT ALL PRIVILEGES ON haiya_user.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_video.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_comment.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_like.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_follow.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_gateway.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_registry.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_message.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_live.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_recommend.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_search.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_payment.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_ecommerce.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_ad.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_ad_analytics.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_analytics.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_ar_vr.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_article.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_audio.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_bi.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_camera.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_campaign.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_cart.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_content_security.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_copyright.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_creator_tools.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_dashboard.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_data_collector.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_data_warehouse.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_database_sharding.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_distributed_transaction.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_editor.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_effect.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_feature_engineering.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_gift.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_group.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_im.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_live_interaction.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_localization.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_logistics.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_media_processing.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_mesh.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_minor_protection.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_ml_platform.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_moderation.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_notification.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_order.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_product.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_qanda.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_real_time_processing.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_storage.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_story.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_supply_chain.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_topic.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_transcoder.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_translation.* TO 'haiya'@'%';
GRANT ALL PRIVILEGES ON haiya_virtual_tryon.* TO 'haiya'@'%';

GRANT ALL PRIVILEGES ON haiya_user.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_video.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_comment.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_like.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_follow.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_gateway.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_registry.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_message.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_live.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_recommend.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_search.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_payment.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_ecommerce.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_ad.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_ad_analytics.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_analytics.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_ar_vr.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_article.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_audio.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_bi.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_camera.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_campaign.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_cart.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_content_security.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_copyright.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_creator_tools.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_dashboard.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_data_collector.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_data_warehouse.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_database_sharding.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_distributed_transaction.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_editor.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_effect.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_feature_engineering.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_gift.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_group.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_im.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_live_interaction.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_localization.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_logistics.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_media_processing.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_mesh.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_minor_protection.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_ml_platform.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_moderation.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_notification.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_order.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_product.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_qanda.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_real_time_processing.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_storage.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_story.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_supply_chain.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_topic.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_transcoder.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_translation.* TO 'haiya'@'localhost';
GRANT ALL PRIVILEGES ON haiya_virtual_tryon.* TO 'haiya'@'localhost';

-- 刷新权限
FLUSH PRIVILEGES;

-- 显示创建的数据库
SHOW DATABASES LIKE 'haiya_%';