server:
  port: 8085

spring:
  application:
    name: service-follow
    
  datasource:
    url: jdbc:h2:mem:followdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  h2:
    console:
      enabled: true
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level:
    com.haiya: DEBUG